### ISSUE TITLE
How to set image size and multiple titles

### ISSUE THREAD

**Issue by AP2020C** [nathonius/obsidian-auto-class#51]
Question 1:
What rule should I enter to have the images at 40px, if they don't have a different size?
These codes did not work
img-max-width:40px;
img:not([style*="width"]) {    width: 40px !important;}
--image-max-width:40px;
--image-width:40px;
img-width:40px;
--img-max-width:40px;

Question 2:
I used
--h2-color: blue;
and it works.
However, I would have expected that
--h*-color: blue;
would act on all titles. What syntax should I use?

**Comment by nathonius** [comment]
Most of this is not valid CSS. To use this plugin, you need to define a class in the plugin settings,`small-images` for example, and set it to apply on certain files.

Once that is done, a snippet like this would do what you want:

```css
.small-images img {
  width: 40px;
}
```

As for header colors, I don't believe there are stock header color variables, those are coming from your theme or another plugin I'd wager.
